config/routes.rb
Sge::Application.routes.draw do

  root 'home#index'

  resources :patients

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :person
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_one :person, dependent: :destroy
  accepts_nested_attributes_for :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :address, dependent: :destroy
  has_one :contact, dependent: :destroy
  belongs_to :patient

  validates :name, :birth, :gender, presence: true
  validates_uniqueness_of :cpf, :rg, allow_blank: true

  accepts_nested_attributes_for :address, :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
    @patient.build_person
    @patient.person.build_address
    @patient.person.build_contact
  end

  def create
    @patient = Patient.new post_params
    if @patient.save
      redirect_to patients_path, notice: "Paciente criado com sucesso"
    else
      render action: "new"
    end
  end

  private
  def post_params
    params.require(:patient).permit(
      person_attributes: [:name, :birth, :gender, :cpf, :rg,
        address_attributes: [:street, :number, :complement, :district, :city, :state, :zip],
        contact_attributes: [:email, :mobile, :landline, :business]
    ])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def states
    [["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>SGE</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="ui menu <%= "tiered" if ["patients"].include?(params[:controller]) %>">
    <div class="menu">
      <%= link_to raw("<i class=\"home icon\"></i>Início"), root_path, class: "item#{params[:controller] == "home" ? " active" : nil }" %>
      <%= link_to raw("<i class=\"users icon\"></i>Pacientes"), patients_path, class: "item#{params[:controller] == "patients" ? " active" : nil }" %>
      <a class="item">
        <i class="medkit icon"></i>
        Planos de saúde
      </a>
    </div>
    <%= yield :submenu %>
  </div>

  <%= yield %>
 
  </body>
</html>

app/views/patients/_address.html.erb
<div class="field street">
  <%= address.label :street, "Logradouro" %>
  <%= address.text_field :street, placeholder:"rua/avenida" %>
</div>
<div class="two fields">
  <div class="field number">
    <%= address.label :number, "Número" %>
    <%= address.text_field :number, placeholder:"número" %>
  </div>
  <div class="field complement">
    <%= address.label :complement, "Complemento" %>
    <%= address.text_field :complement, placeholder:"complemento" %>
  </div>
</div>
<div class="two fields">
  <div class="field district">
    <%= address.label :district, "Bairro" %>
    <%= address.text_field :district, placeholder:"bairro" %>
  </div>
  <div class="field"></div>
</div>
<div class="two fields">
  <div class="field city">
    <%= address.label :city, "Cidade" %>
    <%= address.text_field :city, placeholder:"cidade" %>
  </div>
  <div class="field"></div>
</div>
<div class="field state">
  <%= address.label :state, "Estado" %>
  <div class="ui selection dropdown state">
    <%= address.hidden_field :state %>
    <div class="default text">estado</div>
    <i class="dropdown icon"></i>
    <div class="menu">
      <% states.each do |state| %>
        <div class="item" data-value="<%= state.last %>"><%= state.first %></div>
      <% end %>
    </div>
  </div>
</div>
<div class="two fields">
  <div class="field zip">
    <%= address.label :zip, "CEP" %>
    <%= address.text_field :zip, placeholder:"cep" %>
  </div>
  <div class="field"></div>
</div>

app/views/patients/_contact.html.erb
<div class="field email">
  <%= contact.label :email, "E-mail" %>
  <div class="ui left icon input">
    <%= contact.text_field :email, placeholder:"e-mail" %> 
    <i class="mail icon"></i>
  </div>
</div>
<div class="two fields">
  <div class="field landline">
    <%= contact.label :landline, "Telefone residencial" %>
    <div class="ui left icon input">
      <%= contact.text_field :landline, placeholder:"telefone residencial" %> 
      <i class="phone icon"></i>
    </div>
  </div>
  <div class="field mobile">
    <%= contact.label :mobile, "Celular" %>
    <div class="ui left icon input">
      <%= contact.text_field :mobile, placeholder:"celular" %> 
      <i class="mobile icon"></i>
    </div>
  </div>
</div>
<div class="two fields">
  <div class="field business">
    <%= contact.label :business, "Telefone comercial" %>
    <%= contact.text_field :business, placeholder:"telefone comercial" %> 
  </div>
  <div class="field"></div>
</div>

app/views/patients/_patient.html.erb
<h3 class="ui left floated header">Dados pessoais</h3>
<div class="ui clearing divider"></div>
<%= render 'shared/error_messages', object: patient.object %>

<%= patient.fields_for :person do |person| %>
  <%= render "person", person: person %>
<% end %>

<%= patient.submit "Salvar", class: "ui blue submit button" %>

<%= javascript_tag do %>
  <% if patient.object.errors[:"person.cpf"].any? %>
    $('.field.cpf').addClass('error');
  <% end %>
  <% if patient.object.errors[:"person.rg"].any? %>
    $('.field.rg').addClass('error');
  <% end %>
<% end %>

app/views/patients/_person.html.erb
<div class="field name">
  <%= person.label :name, "Nome completo" %>
  <div class="ui left labeled icon input">
    <%= person.text_field :name, placeholder:"nome sobrenome" %> 
    <i class="user icon"></i>
    <div class="ui corner label"><i class="icon asterisk"></i></div>
  </div>
</div>
<div class="two fields">
  <div class="field birth">
    <%= person.label :birth, "Nascimento" %>
    <div class="ui left labeled icon input">
      <%= person.text_field :birth, placeholder:"dd/mm/aaaa" %>
      <i class="date basic icon"></i>
      <div class="ui corner label"><i class="icon asterisk"></i></div>
    </div>
  </div>
  <div class="field"></div>
</div>
<div class="two fields">
  <div class="field cpf">
    <%= person.label :cpf, "CPF" %>
    <%= person.text_field :cpf, placeholder:"cpf" %>
  </div>
  <div class="field rg">
    <%= person.label :rg, "RG" %>
    <%= person.text_field :rg, placeholder:"rg" %>
  </div>
</div>          
<div class="field">
  <%= person.label :gender, "Sexo" %>
  <div class="ui selection dropdown">
    <%= person.hidden_field :gender %>
    <div class="default text">sexo</div>
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item" data-value="male">Masculino</div>
      <div class="item" data-value="female">Feminino</div>
    </div>
  </div>
</div>
<h3 class="ui left floated header">Contato</h3>
<div class="ui clearing divider"></div>
<%= person.fields_for :contact do |contact| %>
  <%= render "contact", contact: contact %>
<% end %>

<h3 class="ui left floated header">Endereço</h3>
<div class="ui clearing divider"></div>
<%= person.fields_for :address do |address| %>
  <%= render "address", address: address %>
<% end %>

app/views/patients/index.html.erb
<% content_for :submenu do %>
  <div class="ui sub menu">
    <%= link_to "Listar", patients_path, class: "item active" %>
    <%= link_to "Adicionar", new_patient_path, class: "item" %>
  </div>
<% end %>

<% @patients.each do |patient| %>
  <p><%= patient.person.name %></p>
<% end %>

<table class="ui table segment">
  <thead>
    <tr><th>Name</th>
    <th>Status</th>
    <th>Notes</th>
  </tr></thead>
  <tbody>
    <tr>
      <td>Jamie</td>
      <td>Approved</td>
      <td>Requires call</td>
    </tr>
    <tr class="active">
      <td class="active">John</td>
      <td>Selected</td>
      <td>None</td>
    </tr>
    <tr>
      <td>Jamie</td>
      <td>Approved</td>
      <td>Requires call</td>
    </tr>
    <tr>
      <td>Jill</td>
      <td>Approved</td>
      <td>None</td>
    </tr>
  </tbody>
</table>

app/views/patients/new.html.erb
<% content_for :submenu do %>
  <div class="ui sub pointing menu">
    <%= link_to "Listar", patients_path, class: "item" %>
    <%= link_to "Adicionar", new_patient_path, class: "item active" %>
  </div>
<% end %>

<div class="ui one column page grid">
  <div class="column">
    <div class="ui form segment">
      <%= form_for @patient, url: {action: "create"} do |patient| %>
        <%= render 'patient', patient: patient %>
      <% end %>
    </div>
  </div>
</div>


<%= javascript_tag do %>
  var zipcode = '';
  $('.ui.form').form({
    personName: {
      identifier: 'patient_person_attributes_name',
      rules: [
        {
          type: 'empty',
          prompt: 'Por favor entre com o nome completo'
        }
      ]
    },
    personBirth: {
      identifier: 'patient_person_attributes_birth',
      rules: [
        {
          type:   'empty',
          prompt: 'Por favor entre com uma data'
        },
        {
          type:   'date',
          prompt: 'Por favor entre com uma data válida'
        }
      ]
    },
    personGender: {
      identifier: 'patient_person_attributes_gender',
      rules: [
        {
          type: 'empty',
          prompt: 'Por favor escolha um sexo'
        }
      ]
    },
    addressZip: {
      identifier: 'patient_person_attributes_address_attributes_zip',
      rules: [
        {
          type:   'smartInteger',
          prompt: 'Por favor entre somente com números'
        },
        {
          type:   'smartLength[8]',
          prompt: 'Por favor entre com apenas oito números'
        }
      ]
    }
  }, {
    inline: 'true',
    on: 'submit',
    onFailure: function(){
      $('<%= browser.chrome? ? "body" : "html" %>').animate({
        scrollTop: $('.field.error:first').offset().top - 21
      });
      return false;
    }
  });

  $('#patient_person_attributes_address_attributes_zip').blur(function(obj){
    var current = $(this).val();
    if(current && $.fn.form.settings.rules.smartInteger(current) && $.fn.form.settings.rules.smartLength(current, 8) && zipcode != current) {
      zipcode = current;
      $('.ui.form').addClass('loading');
      $.get("http://cep.republicavirtual.com.br/web_cep.php", {formato: 'json',cep: zipcode}, function(res){
        fillAddress(res);
      }).always(function(){
        $('.ui.form').removeClass('loading');
      });
    }
  });

  $('.ui.selection.dropdown').dropdown();

  $.datepicker.setDefaults($.datepicker.regional["pt-BR"]);
  $('#patient_person_attributes_birth').datepicker({
    changeMonth: true,
    changeYear: true,
    yearRange: '1900:' + new Date().getFullYear()
  });
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="ui error message" >
    <i class="close icon"></i>
    <div class="header">
      O formulário contém <%= pluralize(object.errors.count, "erro") %>
    </div>
    <ul class="list">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

  <%= javascript_tag do %>
    $('.ui.form').addClass('error');
    $('.message .close').on('click', function() {
      $(this).closest('.message').fadeOut();
    });
  <% end %>
<% end %>